context:
  name: sasctl
  version: "1.11.1"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/5e/94/8d2c7fd826d0c71c2e567f433c55282e6871230bc7cb244988f329c91fd9/${{ name }}-${{ version }}.tar.gz
  sha256: 8315d4612304b7afde12c453af0d46bf52d2eae8ef829595e8c8975c1dfca8f3

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - dill
    - pandas >=0.24.0
    - requests
    - pyyaml
    - packaging
    - GitPython
    - scikit-learn

tests:
  - python:
      imports:
      - sasctl
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/sassoftware/python-sasctl/
  summary: 'The sasctl package enables easy communication between the SAS Viya platform and a Python runtime. It can be used as a module or as a command line interface.'
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/sassoftware/python-sasctl/

extra:
  recipe-maintainers:
    - EllaBootQC
