context:
  name: sasctl
  version: "1.11.5"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/6f/4e/44ff6711fd407a30271b9792094db75ec48d24fce8476e8c47f63d78e949/sasctl-${{ version }}.tar.gz
  sha256: 9b9d5e8d344da6bc3eab1fc2fab1b65202deb0158e1383297185b5b657a15607

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - dill
    - pandas >=0.24.0
    - requests
    - pyyaml
    - packaging
    - GitPython
    - scikit-learn

tests:
  - python:
      imports:
        - sasctl
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/sassoftware/python-sasctl/
  summary: 'The sasctl package enables easy communication between the SAS Viya platform and a Python runtime. It can be used as a module or as a command line interface.'
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/sassoftware/python-sasctl/

extra:
  recipe-maintainers:
    - EllaBootQC
